(easy) delete unused lambda capture 'kCount'
Summary:
as title:

```
/usr/ports/net/fbzmq/work/fbzmq-2020.09.07.00/fbzmq/async/tests/ZmqEventLoopTest.cpp:292:36: error: lambda capture 'kCount' is not required to be captured for this use [-Werror,-Wunused-lambda-capture]
    evl.scheduleTimeoutAt(now, [i, kCount, &count, &evl]() noexcept {
                                 ~~^~~~~~
/usr/ports/net/fbzmq/work/fbzmq-2020.09.07.00/fbzmq/async/tests/ZmqEventLoopTest.cpp:320:36: error: lambda capture 'kCount' is not required to be captured for this use [-Werror,-Wunused-lambda-capture]
    evl.scheduleTimeoutAt(now, [i, kCount, &count, &evl]() noexcept {
                                 ~~^~~~~~
2 errors generated.
```

Reviewed By: xiangxu1121

Differential Revision: D29121894

fbshipit-source-id: 35d28239fe0228fc16d9a9ea529b3cfa0aa6b953