fbzmq: Fix compile error on Fedora 30
Summary:
Fix this compile error:

```
In file included from /home/foo/code/fb/fbzmq/fbzmq/zmq/Zmq.h:12,
                 from /home/foo/code/fb/fbzmq/fbzmq/examples/client/ZmqClient.h:13,
                 from /home/foo/code/fb/fbzmq/fbzmq/examples/client/ZmqClient.cpp:9:
/home/foo/code/fb/fbzmq/fbzmq/zmq/Message.h: In instantiation of ‘folly::Expected<T, fbzmq::Error> fbzmq::Message::read() const [with T = unsigned int; std::enable_if_t<std::is_fundamental<typename std::decay<_Tp>::type>::value>* <anonymous> = 0]’:
/home/foo/code/fb/fbzmq/fbzmq/examples/client/ZmqClient.cpp:72:55:   required from here
/home/foo/code/fb/fbzmq/fbzmq/zmq/Message.h:102:25: error: redundant move in return statement [-Werror=redundant-move]
  102 |     return std::move(obj);
      |                         ^
/home/foo/code/fb/fbzmq/fbzmq/zmq/Message.h:102:25: note: remove ‘std::move’ call
cc1plus: all warnings being treated as errors
make[2]: *** [fbzmq/CMakeFiles/zmq_client_example.dir/build.make:96: fbzmq/CMakeFiles/zmq_client_example.dir/examples/client/ZmqClient.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:349: fbzmq/CMakeFiles/zmq_client_example.dir/all] Error 2
make: *** [Makefile:172: all] Error 2
```

Reviewed By: jstrizich

Differential Revision: D22777877

fbshipit-source-id: 1be5e1d0631949c2320116e5bcfcb58b6912f931