Fix CMakeFiles.txt Example/Test thrift race.
Summary:
Example.thrift and Test.thrift are used to build two
separate libraries but were using the same custom command to generate
both.  As a result a parallel cmake calls the custom command twice
(once per each library) which in turn generates each file twice.
This will sometimes result in a file being regenerated while it
is being compiled resulting in an incomplete compile.  For example:

ibfbzmq-examples-if.a(Example_types.cpp.o): In function `apache::thrift::detail::TEnumMapFactory<fbzmq::example::thrift::Command, fbzmq::example::thrift::Command>::makeNamesToValuesMap()':
/usr/include/thrift/lib/cpp/Thrift.h:191: undefined reference to `fbzmq::example::thrift::_CommandEnumDataStorage::values'
/usr/include/thrift/lib/cpp/Thrift.h:190: undefined reference to `fbzmq::example::thrift::_CommandEnumDataStorage::names'
libfbzmq-examples-if.a(Example_types.cpp.o): In function `apache::thrift::detail::TEnumMapFactory<fbzmq::example::thrift::Command, fbzmq::example::thrift::Command>::makeValuesToNamesMap()':
/usr/include/thrift/lib/cpp/Thrift.h:184: undefined reference to `fbzmq::example::thrift::_CommandEnumDataStorage::values'
/usr/include/thrift/lib/cpp/Thrift.h:184: undefined reference to `fbzmq::example::thrift::_CommandEnumDataStorage::values'
libfbzmq-examples-if.a(Example_types.cpp.o):(.rodata+0x740): undefined reference to `fbzmq::example::thrift::_CommandEnumDataStorage::names'
libfbzmq-examples-if.a(Example_types.cpp.o):(.rodata+0x748): undefined reference to `fbzmq::example::thrift::_CommandEnumDataStorage::names'
libfbzmq-examples-if.a(Example_types.cpp.o):(.rodata+0x750): undefined reference to `fbzmq::example::thrift::_CommandEnumDataStorage::values'
libfbzmq-examples-if.a(Example_types.cpp.o):(.rodata+0x758): undefined reference to `fbzmq::example::thrift::_CommandEnumDataStorage::values'
collect2: error: ld returned 1 exit status

Reviewed By: saifhhasan

Differential Revision: D4981625

fbshipit-source-id: a0384d0b79af55dcae0a1b59a21c9cf450b6b7df